apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv
spec:
    capacity:
       storage: 100Gi
    accessModes:
       - ReadWriteMany
    rbd:
       monitors: 
           - 192.168.1.47:6789
       pool: pv_data
       image: cephfs
       user: admin
       secretRef: 
           name: ceph-key-secret
       fsType: ext4
       readOnly: false


