apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{name}}
spec:
    capacity:
       storage: {{storage}}
    accessModes:
       - {{accessModes}}
    rbd:
       monitors: 
           - {{monitors}}
       pool: {{pool}}
       image: {{image}}
       user: {{user}}
       secretRef: 
           name: {{secret}}
       fsType: {{fsType}}
       readOnly: {{readOnly}}
